# Name of Website
title: Welcome to Xianghao's Website

# Your name to show in the footer
author: Xianghao Kong

# Theme Template 
theme: jekyll-theme-cayman

# --- List of links in the navigation bar --- #
navbar-links:
  About Me: "index"

  My Sketch: "sketch" 
  
  Author's home: "https://kxh001.github.io/"
  
# --- Logo --- #

# Image to show in the navigation bar - works best with a square image
# Remove this parameter if you don't want an image in the navbar
avatar: "./Image/Portrait.jpg"
# By default, the image is cut into a circle. You can disable this behaviour by setting 'round-avatar: false'
round-avatar: true

